//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.image` struct is generated, and contains static references to 1 images.
  struct image {
    /// Image `questionmark`.
    static let questionmark = Rswift.ImageResource(bundle: R.hostingBundle, name: "questionmark")
    
    /// `UIImage(named: "questionmark", bundle: ..., traitCollection: ...)`
    static func questionmark(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.questionmark, compatibleWith: traitCollection)
    }
    
    /// This `R.image.demoPictures` struct is generated, and contains static references to 3 images.
    struct demoPictures {
      /// Image `24652084979_33cf407520_o`.
      static let _33cf407520_o = Rswift.ImageResource(bundle: R.hostingBundle, name: "DemoPictures/24652084979_33cf407520_o")
      /// Image `25385620682_4ffcfc301e_o`.
      static let _4ffcfc301e_o = Rswift.ImageResource(bundle: R.hostingBundle, name: "DemoPictures/25385620682_4ffcfc301e_o")
      /// Image `6792282444_f100e81868_o`.
      static let _f100e81868_o = Rswift.ImageResource(bundle: R.hostingBundle, name: "DemoPictures/6792282444_f100e81868_o")
      
      /// `UIImage(named: "24652084979_33cf407520_o", bundle: ..., traitCollection: ...)`
      static func _33cf407520_o(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
        return UIKit.UIImage(resource: R.image.demoPictures._33cf407520_o, compatibleWith: traitCollection)
      }
      
      /// `UIImage(named: "25385620682_4ffcfc301e_o", bundle: ..., traitCollection: ...)`
      static func _4ffcfc301e_o(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
        return UIKit.UIImage(resource: R.image.demoPictures._4ffcfc301e_o, compatibleWith: traitCollection)
      }
      
      /// `UIImage(named: "6792282444_f100e81868_o", bundle: ..., traitCollection: ...)`
      static func _f100e81868_o(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
        return UIKit.UIImage(resource: R.image.demoPictures._f100e81868_o, compatibleWith: traitCollection)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  fileprivate init() {}
}
