author: Przemysław Wośko, Andrzej Michnia
author_url: http://girappe.com
module: SwiftyMocky
sourcekitten_sourcefile: docs.json
module_version: 0.0.9
github_url: https://github.com/MakeAWishFoundation/SwiftyMocky
copyright: 'Copyright © 2017 MakeAWishFoundation. All rights reserved.'
readme: guides/Overview.md
documentation: guides/*.md

custom_categories:
  - name: Guides
    children:
      - Overview
      - Supported features
      - Installation
      - Setup in project
      - Matcher support for not Equatable
      - Handling Generics
      - Examples
      - Custom Subspec
      - Add XCode generate action
      - Known issues
      - CHANGELOG

  - name: Global methods
    children:
      - Given(_:_:_:)
      - Perform(_:_:)
      - Verify(_:_:file:line:)
      - Verify(_:_:_:file:line:)

  - name: Configuration
    children:
      - StubbingPolicy
      - SequencingPolicy

  - name: Types
    children:
      - Mock
      - StaticMock
      - Parameter
      - Matcher
      - Countable
      - Count
      - Stubber<ReturnedValue>
      - StubberThrows<ReturnedValue>

  - name: Generics
    children:
      - GenericAttribute
      - GenericAttributeType

  - name: Deprecated
    children:
      - VerifyProperty(_:_:file:line:)
      - VerifyProperty(_:_:_:file:line:)
