language: objective-c

os: osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10

notifications:
  #slack: // TODO:
  email: false

install:
  - if [ `uname` == "Linux" ] ; then
        curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash ;
    fi

script:
  # - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash certs.sh; fi' # certs for macos app
  - rake pods
  - rake mock
  # - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then fastlane mac test; fi' # unable to run macos tests on CI now - turning off on CI
  - fastlane ios test
  - fastlane tvos test

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725
